export const homeProcedures = [
  {
    step: "01",
    title: "報名",
    description: [
      "任何時間，想報就報。",
      "網上報名方便快捷，只需填妥幾條問題，",
      "即可完成報名後即有專人1 對 1 跟進",
    ],
    imageUrl: "/images/homepage/homepageProcess01.png",
    imageClass: "scale-150 left-[20vh] bottom-0",
    bgColor: "bg-yellow-700",
    url: "/application",
  },
  {
    step: "02",
    title: "筆試",
    description: ["提供免費模擬筆試，", "試題簡單易明，熟讀合格冇難度"],
    imageUrl: "/images/homepage/homepageProcess02.png",
    imageClass: "left-0 bottom-0",
    bgColor: "bg-gray-200",
    url: "/mocktest",
  },
  {
    step: "03",
    title: "學車",
    description: [
      "學生可於學神的教車師傅列表中，",
      "根據師傅資料、提供的車型車款，",
      "選擇合適你的學神師傅",
    ],
    imageUrl: "/images/homepage/homepageProcess03.png",
    imageClass: "invert bottom-0 left-[20vh]",
    bgColor: "bg-zinc-500",
    url: "/",
  },
  {
    step: "04",
    title: "路試",
    description: [
      "準備左咁耐，謹記駕駛訓練課堂學到的，",
      "路試時好好發揮，注意道路安全，",
      "1 take pass無難度",
    ],
    imageUrl: "/images/homepage/homepageProcess04.jpg",
    imageClass: "top-0 left-9 scale-150 filter",
    bgColor: "bg-slate-800",
    url: "/roadtest-info",
  },
  {
    step: "05",
    title: "攞牌",
    description: [
      "恭喜晒！路試合格之後，",
      "可申請暫準駕駛執照（P牌）。",
      "P牌掛滿一年，順利過渡就可以申領正式駕駛執照",
    ],
    imageUrl: "/images/homepage/homepageProcess05.png",
    imageClass: "right-0",
    bgColor: "bg-red-500",
    url: null,
  },
];
